/**
 * Admin API Client
 * 
 * API functions for admin dashboard features including:
 * - Model health monitoring
 * - Analysis statistics
 * - User statistics
 * - User reports management
 * - User management
 */

import { authApiRequest } from './client';

const API_BASE =
  import.meta.env.VITE_API_BASE_URL?.replace(/\/$/, '') ||
  'http://localhost:8000/api';

function buildAnalysisStatsCsv(stats = {}, categories = [], metadata = {}) {
  const rows = [];

  const formatDateTime = (value) => {
    if (!value) return 'N/A';
    const date = new Date(value);
    if (Number.isNaN(date.getTime())) return String(value);
    return date.toISOString().replace('T', ' ').replace('Z', ' UTC').split('.')[0];
  };

  const formatDateOnly = (value) => {
    if (!value) return '';
    const date = new Date(value);
    if (Number.isNaN(date.getTime())) return String(value).slice(0, 10);
    return date.toISOString().slice(0, 10);
  };

  const totalCount = stats.total_count || 0;
  const previousTotalCount = stats.previous_total_count || 0;
  const scamCount = stats.scam_count || 0;
  const previousScamCount = stats.previous_scam_count || 0;
  const highRiskCount = stats.high_risk_count || 0;
  const mediumRiskCount = stats.medium_risk_count || 0;
  const lowRiskCount = stats.low_risk_count || 0;
  const legitimateCount = stats.legitimate_count || 0;

  const pct = (value, total) => (total ? Number(((value / total) * 100).toFixed(2)) : 0);
  const changePct = (current, previous) => (previous ? Number((((current - previous) / previous) * 100).toFixed(2)) : 0);

  const generatedAtUtc = new Date().toISOString().replace('T', ' ').replace('Z', ' UTC').split('.')[0];
  const filtersApplied = metadata.filtersApplied || '';
  const generatedBy = metadata.generatedBy || 'admin';
  const timezone = metadata.timezone || Intl.DateTimeFormat().resolvedOptions().timeZone || 'UTC';

  rows.push(['Metadata', 'Value']);
  rows.push(['Generated By', generatedBy]);
  rows.push(['Generated At (UTC)', generatedAtUtc]);
  rows.push(['Timezone', timezone]);
  rows.push(['Filters Applied', filtersApplied]);
  rows.push([]);

  rows.push(['Summary Metric', 'Value']);
  rows.push(['Period', stats.period || 'all_time']);
  rows.push(['Start Date', formatDateOnly(stats.start_date)]);
  rows.push(['End Date', formatDateOnly(stats.end_date)]);
  rows.push(['Calculated At (UTC)', formatDateTime(stats.calculated_at || new Date().toISOString())]);
  rows.push(['Total Analyses', totalCount]);
  rows.push(['Previous Total Analyses', previousTotalCount]);
  rows.push(['Total Analyses Change (%)', changePct(totalCount, previousTotalCount)]);
  rows.push(['Scams Detected', scamCount]);
  rows.push(['Previous Scams Detected', previousScamCount]);
  rows.push(['Scam Detection Change (%)', changePct(scamCount, previousScamCount)]);
  rows.push(['Scam Detection Rate (%)', Number((stats.scam_rate_percent || 0).toFixed(2))]);
  rows.push(['High Risk Count', highRiskCount]);
  rows.push(['High Risk Rate (%)', pct(highRiskCount, totalCount)]);
  rows.push(['Medium Risk Count', mediumRiskCount]);
  rows.push(['Medium Risk Rate (%)', pct(mediumRiskCount, totalCount)]);
  rows.push(['Low Risk Count', lowRiskCount]);
  rows.push(['Low Risk Rate (%)', pct(lowRiskCount, totalCount)]);
  rows.push(['Legitimate Count', legitimateCount]);
  rows.push(['Legitimate Rate (%)', pct(legitimateCount, totalCount)]);
  rows.push(['Top Scam Category', stats.top_scam_category || 'N/A']);

  rows.push([]);
  rows.push(['Confidence Distribution', 'Bucket', 'Count', 'Share (%)']);
  (stats.confidence_distribution || []).forEach((bucket) => {
    rows.push([
      'Confidence',
      bucket.bucket || '',
      bucket.count || 0,
      Number((bucket.percentage || 0).toFixed(2)),
    ]);
  });

  rows.push([]);
  rows.push(['Top Scam Categories', 'Rank', 'Category', 'Detections', 'Share (%)', 'Severity']);
  (categories || []).forEach((category, idx) => {
    rows.push([
      'Category',
      idx + 1,
      category.category || 'Unknown',
      category.count || 0,
      Number((category.percentage || 0).toFixed(2)),
      category.severity || 'unknown',
    ]);
  });

  rows.push([]);
  rows.push(['Daily Activity', 'Date', 'Total', 'Scams', 'Legitimate', 'Detection Rate (%)']);
  (stats.daily_counts || []).forEach((day) => {
    const total = day.total || 0;
    const scams = day.scams || 0;
    rows.push([
      'Day',
      formatDateOnly(day.date),
      total,
      scams,
      day.legitimate || 0,
      pct(scams, total),
    ]);
  });

  rows.push([]);
  rows.push(['Previous Period Daily Activity', 'Date', 'Total', 'Scams', 'Legitimate', 'Detection Rate (%)']);
  (stats.previous_daily_counts || []).forEach((day) => {
    const total = day.total || 0;
    const scams = day.scams || 0;
    rows.push([
      'Previous Day',
      formatDateOnly(day.date),
      total,
      scams,
      day.legitimate || 0,
      pct(scams, total),
    ]);
  });

  return rows
    .map((row) => row.map((value) => {
      const cell = value == null ? '' : String(value);
      if (cell.includes(',') || cell.includes('"') || cell.includes('\n')) {
        return `"${cell.replace(/"/g, '""')}"`;
      }
      return cell;
    }).join(','))
    .join('\n');
}

// ==================== Model Health ====================

/**
 * Get current model health metrics (GPU, CPU, Memory, etc.)
 * @returns {Promise<Object>} Model health data
 */
export async function getModelHealth() {
  return authApiRequest('/admin/model-health/', {
    method: 'GET',
  });
}

/**
 * Get model health summary with status indicators
 * @returns {Promise<Object>} Health summary
 */
export async function getModelHealthSummary() {
  return authApiRequest('/admin/model-health/summary/', {
    method: 'GET',
  });
}

// ==================== Analysis Statistics ====================

/**
 * Get analysis statistics
 * @param {Object} params - Query parameters
 * @param {string} params.startDate - Start date (YYYY-MM-DD)
 * @param {string} params.endDate - End date (YYYY-MM-DD)
 * @param {string} params.period - Period grouping (day|week|month|year|all_time)
 * @returns {Promise<Object>} Analysis statistics
 */
export async function getAnalysisStats({ startDate, endDate, period } = {}) {
  const params = new URLSearchParams();
  if (startDate) params.append('start_date', startDate);
  if (endDate) params.append('end_date', endDate);
  if (period) params.append('period', period);
  
  const queryString = params.toString();
  const url = `/admin/analysis-stats/${queryString ? `?${queryString}` : ''}`;
  
  return authApiRequest(url, {
    method: 'GET',
  });
}

/**
 * Get top scam categories
 * @param {Object} params - Query parameters
 * @param {string} params.startDate - Start date
 * @param {string} params.endDate - End date
 * @param {number} params.limit - Max categories to return (default 10)
 * @returns {Promise<Object>} Top categories data
 */
export async function getTopScamCategories({ startDate, endDate, period, limit = 10 } = {}) {
  const params = new URLSearchParams();
  if (startDate) params.append('start_date', startDate);
  if (endDate) params.append('end_date', endDate);
  if (period) params.append('period', period);
  if (limit) params.append('limit', limit.toString());
  
  const queryString = params.toString();
  const url = `/admin/analysis-stats/top-categories/${queryString ? `?${queryString}` : ''}`;
  
  return authApiRequest(url, {
    method: 'GET',
  });
}

/**
 * Export analysis statistics as CSV or Excel-compatible CSV.
 * @param {Object} params - Query parameters
 * @param {string} params.startDate - Start date
 * @param {string} params.endDate - End date
 * @param {string} params.period - Period grouping
 * @param {string} params.format - csv|excel
 * @param {number} params.limit - Number of top categories to include
 * @returns {Promise<{blob: Blob, filename: string}>}
 */
export async function exportAnalysisStats({
  startDate,
  endDate,
  period,
  format = 'csv',
  limit = 10,
  fallbackData,
  fallbackMeta,
  preferClientExport = false,
} = {}) {
  const params = new URLSearchParams();
  if (startDate) params.append('start_date', startDate);
  if (endDate) params.append('end_date', endDate);
  if (period) params.append('period', period);
  if (format) params.append('format', format);
  if (limit) params.append('limit', limit.toString());

  const queryString = params.toString();
  const url = `${API_BASE}/admin/analysis-stats/export/${queryString ? `?${queryString}` : ''}`;

  const headers = {};
  const accessToken = window.localStorage.getItem('access_token');
  if (accessToken) {
    headers.Authorization = `Bearer ${accessToken}`;
  }

  const localStats = fallbackData?.stats;
  const localCategories = fallbackData?.categories;
  const localMeta = fallbackMeta || {};

  if (preferClientExport && localStats) {
    const csvContent = buildAnalysisStatsCsv(localStats || {}, Array.isArray(localCategories) ? localCategories : [], localMeta);
    const blobType = format === 'excel' ? 'application/vnd.ms-excel' : 'text/csv';
    const extension = format === 'excel' ? 'xls' : 'csv';
    const safePeriod = period || 'all_time';
    const filename = `analysis_stats_${safePeriod}_${new Date().toISOString().slice(0, 10).replace(/-/g, '')}.${extension}`;
    return {
      blob: new Blob([csvContent], { type: blobType }),
      filename,
    };
  }

  const response = await fetch(url, {
    method: 'GET',
    headers,
  });

  if (!response.ok) {
    if (response.status === 404) {
      let statsForExport = localStats;
      let categoriesForExport = Array.isArray(localCategories) ? localCategories : [];

      if (!statsForExport) {
        const [statsRes, categoriesRes] = await Promise.all([
          getAnalysisStats({ startDate, endDate, period }),
          getTopScamCategories({ startDate, endDate, period, limit }),
        ]);

        if (!statsRes?.success) {
          throw new Error('Failed to load analysis stats for export fallback');
        }

        statsForExport = statsRes.data || {};
        categoriesForExport = categoriesRes?.success ? (categoriesRes.data || []) : [];
      }

      const csvContent = buildAnalysisStatsCsv(statsForExport || {}, categoriesForExport, localMeta);
      const blobType = format === 'excel' ? 'application/vnd.ms-excel' : 'text/csv';
      const extension = format === 'excel' ? 'xls' : 'csv';
      const safePeriod = period || 'all_time';
      const filename = `analysis_stats_${safePeriod}_${new Date().toISOString().slice(0, 10).replace(/-/g, '')}.${extension}`;
      return {
        blob: new Blob([csvContent], { type: blobType }),
        filename,
      };
    }

    let message = `Failed to export analysis statistics (${response.status})`;
    try {
      const errorData = await response.json();
      message = errorData?.error?.message || errorData?.message || message;
    } catch {
      // Ignore non-JSON errors
    }
    const error = new Error(message);
    error.status = response.status;
    throw error;
  }

  const blob = await response.blob();
  const contentDisposition = response.headers.get('content-disposition') || '';
  const filenameMatch = contentDisposition.match(/filename="?([^";]+)"?/i);
  const filename = filenameMatch?.[1] || `analysis_stats_export.${format === 'excel' ? 'xls' : 'csv'}`;

  return { blob, filename };
}

// ==================== User Statistics ====================

/**
 * Get user statistics
 * @param {Object} params - Query parameters
 * @param {string} params.startDate - Start date
 * @param {string} params.endDate - End date
 * @param {string} params.period - Period grouping
 * @returns {Promise<Object>} User statistics
 */
export async function getUserStats({ startDate, endDate, period } = {}) {
  const params = new URLSearchParams();
  if (startDate) params.append('start_date', startDate);
  if (endDate) params.append('end_date', endDate);
  if (period) params.append('period', period);
  
  const queryString = params.toString();
  const url = `/admin/user-stats/${queryString ? `?${queryString}` : ''}`;
  
  return authApiRequest(url, {
    method: 'GET',
  });
}

// ==================== User Reports ====================

/**
 * Get user reports with optional filtering
 * @param {Object} params - Query parameters
 * @param {string} params.status - Filter by status (pending|in_progress|resolved|dismissed)
 * @param {number} params.page - Page number (default 1)
 * @param {number} params.limit - Results per page (default 50)
 * @returns {Promise<Object>} Reports list with pagination
 */
export async function getUserReports({ status, page = 1, limit = 50 } = {}) {
  const params = new URLSearchParams();
  if (status) params.append('status', status);
  params.append('page', page.toString());
  params.append('limit', limit.toString());
  
  const queryString = params.toString();
  const url = `/admin/reports/?${queryString}`;
  
  return authApiRequest(url, {
    method: 'GET',
  });
}

/**
 * Get detailed information for a specific report
 * @param {string} reportId - Report ID
 * @returns {Promise<Object>} Report details
 */
export async function getReportDetails(reportId) {
  return authApiRequest(`/admin/reports/${reportId}/detail/`, {
    method: 'GET',
  });
}

/**
 * Update a report's status
 * @param {string} reportId - Report ID
 * @param {Object} data - Update data
 * @param {string} data.status - New status (pending|in_progress|resolved|dismissed)
 * @param {string} data.resolutionNotes - Optional resolution notes
 * @returns {Promise<Object>} Updated report
 */
export async function updateReportStatus(reportId, { status, resolutionNotes }) {
  const body = { status };
  if (resolutionNotes) body.resolution_notes = resolutionNotes;
  
  return authApiRequest(`/admin/reports/${reportId}/`, {
    method: 'PATCH',
    body: JSON.stringify(body),
  });
}

// ==================== User Management ====================

/**
 * Get paginated list of users
 * @param {Object} params - Query parameters
 * @param {string} params.search - Search by email or username
 * @param {string} params.role - Filter by role
 * @param {boolean} params.isActive - Filter by active status
 * @param {boolean} params.isVerified - Filter by verification status
 * @param {number} params.page - Page number (default 1)
 * @param {number} params.limit - Results per page (default 50)
 * @param {string} params.sortBy - Sort field (default 'created_at')
 * @param {string} params.sortOrder - Sort direction (asc|desc)
 * @returns {Promise<Object>} Users list with pagination
 */
export async function getUsers({ 
  search, 
  role, 
  isActive, 
  isVerified, 
  page = 1, 
  limit = 50,
  sortBy = 'created_at',
  sortOrder = 'desc'
} = {}) {
  const params = new URLSearchParams();
  if (search) params.append('search', search);
  if (role) params.append('role', role);
  if (isActive !== undefined) params.append('is_active', isActive.toString());
  if (isVerified !== undefined) params.append('is_verified', isVerified.toString());
  params.append('page', page.toString());
  params.append('limit', limit.toString());
  params.append('sort_by', sortBy);
  params.append('sort_order', sortOrder);
  
  const queryString = params.toString();
  const url = `/admin/users/?${queryString}`;
  
  return authApiRequest(url, {
    method: 'GET',
  });
}

/**
 * Get single user details
 * @param {string} userId - User ID
 * @returns {Promise<Object>} User details
 */
export async function getUser(userId) {
  return authApiRequest(`/admin/users/${userId}/`, {
    method: 'GET',
  });
}

/**
 * Delete a user account
 * @param {string} userId - User ID
 * @param {boolean} hardDelete - If true, permanently delete
 * @returns {Promise<Object>} Deletion result
 */
export async function deleteUser(userId, hardDelete = false) {
  const params = hardDelete ? '?hard_delete=true' : '';
  return authApiRequest(`/admin/users/${userId}/delete/${params}`, {
    method: 'DELETE',
  });
}

/**
 * Admin reset user's password
 * @param {string} userId - User ID
 * @param {string} newPassword - New password
 * @returns {Promise<Object>} Reset result
 */
export async function resetUserPassword(userId, newPassword) {
  return authApiRequest(`/admin/users/${userId}/reset-password/`, {
    method: 'POST',
    body: JSON.stringify({ new_password: newPassword }),
  });
}

/**
 * Update user account status
 * @param {string} userId - User ID
 * @param {string} newStatus - New status ('active', 'inactive', 'suspended')
 * @returns {Promise<Object>} Update result
 */
export async function updateUserStatus(userId, newStatus) {
  return authApiRequest(`/admin/users/${userId}/status/`, {
    method: 'PATCH',
    body: JSON.stringify({ status: newStatus.toLowerCase() }),
  });
}

/**
 * Update a user's roles
 * @param {string} userId - User ID
 * @param {string[]} roles - Array of role names
 * @returns {Promise<Object>} Update result
 */
export async function updateUserRoles(userId, roles) {
  return authApiRequest(`/admin/users/${userId}/roles/`, {
    method: 'PATCH',
    body: JSON.stringify({ roles }),
  });
}
