/**
 * Analytics API Client
 * 
 * Functions for fetching website analytics data from the backend.
 * Requires admin role for all operations.
 */

import apiClient from './client';

function formatDateTime(value) {
  if (!value) return '';
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return String(value);
  return date.toISOString().replace('T', ' ').replace('Z', ' UTC').split('.')[0];
}

function escapeCsvCell(value) {
  const cell = value == null ? '' : String(value);
  if (cell.includes(',') || cell.includes('"') || cell.includes('\n')) {
    return `"${cell.replace(/"/g, '""')}"`;
  }
  return cell;
}

function buildWebsiteAnalyticsCsv(analytics = {}, metadata = {}) {
  const visits = analytics?.visits || {};
  const devices = analytics?.devices || {};
  const topPages = analytics?.top_pages || [];
  const referrers = analytics?.referrers || [];
  const hourlyPattern = analytics?.hourly_pattern || {};
  const recent = analytics?.recent || [];

  const rows = [];
  rows.push(['Metadata', 'Value']);
  rows.push(['Generated By', metadata.generatedBy || 'admin']);
  rows.push(['Generated At (UTC)', formatDateTime(new Date().toISOString())]);
  rows.push(['Timezone', metadata.timezone || Intl.DateTimeFormat().resolvedOptions().timeZone || 'UTC']);
  rows.push(['Period', metadata.period || 'week']);
  rows.push([]);

  rows.push(['Visit Summary', 'Value']);
  rows.push(['Total Visits', visits.total_visits || 0]);
  rows.push(['Unique Visitors', visits.unique_visitors || 0]);
  rows.push(['Authenticated Visits', visits.authenticated_visits || 0]);
  rows.push(['Anonymous Visits', visits.anonymous_visits || 0]);
  rows.push([]);

  rows.push(['Top Pages', 'Rank', 'Path', 'Visit Count']);
  topPages.forEach((page, index) => {
    rows.push(['Page', index + 1, page.path || '', page.visit_count || 0]);
  });
  rows.push([]);

  rows.push(['Device Breakdown', 'Device', 'Visits', 'Share (%)']);
  const deviceEntries = Object.entries(devices).filter(([, count]) => typeof count === 'number');
  const deviceTotal = deviceEntries.reduce((sum, [, count]) => sum + count, 0);
  deviceEntries.forEach(([device, count]) => {
    const share = deviceTotal > 0 ? ((count / deviceTotal) * 100).toFixed(2) : '0.00';
    rows.push(['Device', device, count, share]);
  });
  rows.push([]);

  rows.push(['Hourly Pattern', 'Hour', 'Visits']);
  Object.entries(hourlyPattern)
    .sort(([a], [b]) => Number(a) - Number(b))
    .forEach(([hour, count]) => {
      rows.push(['Hour', hour, count || 0]);
    });
  rows.push([]);

  rows.push(['Top Referrers', 'Rank', 'Referrer', 'Visits']);
  referrers.forEach((item, index) => {
    rows.push(['Referrer', index + 1, item.referrer || 'Direct', item.count || 0]);
  });
  rows.push([]);

  rows.push(['Recent Visits', 'Timestamp (UTC)', 'Path', 'Device', 'Authenticated', 'Referrer']);
  recent.forEach((visit) => {
    rows.push([
      'Visit',
      formatDateTime(visit.timestamp),
      visit.path || '',
      visit.device_type || visit.device || '',
      visit.is_authenticated ? 'Yes' : 'No',
      visit.referrer || 'Direct',
    ]);
  });

  return rows.map((row) => row.map(escapeCsvCell).join(',')).join('\n');
}

/**
 * Get overall visit statistics
 * @param {Object} params - Query parameters
 * @param {string} [params.startDate] - Start date (ISO format)
 * @param {string} [params.endDate] - End date (ISO format)
 * @returns {Promise<Object>} Visit statistics
 */
export const getVisitStatistics = async (params = {}) => {
  const queryParams = new URLSearchParams();
  if (params.startDate) queryParams.append('start_date', params.startDate);
  if (params.endDate) queryParams.append('end_date', params.endDate);
  
  const queryString = queryParams.toString();
  const url = `/analytics/visits/${queryString ? `?${queryString}` : ''}`;
  
  const response = await apiClient.get(url);
  return response.data;
};

/**
 * Get page analytics (visits by path)
 * @param {Object} params - Query parameters
 * @param {string} [params.startDate] - Start date (ISO format)
 * @param {string} [params.endDate] - End date (ISO format)
 * @param {number} [params.limit=10] - Maximum pages to return
 * @returns {Promise<Array>} Page visit statistics
 */
export const getPageAnalytics = async (params = {}) => {
  const queryParams = new URLSearchParams();
  if (params.startDate) queryParams.append('start_date', params.startDate);
  if (params.endDate) queryParams.append('end_date', params.endDate);
  if (params.limit) queryParams.append('limit', params.limit.toString());
  
  const queryString = queryParams.toString();
  const url = `/analytics/pages/${queryString ? `?${queryString}` : ''}`;
  
  const response = await apiClient.get(url);
  return response.data;
};

/**
 * Get device breakdown (desktop, mobile, tablet)
 * @param {Object} params - Query parameters
 * @param {string} [params.startDate] - Start date (ISO format)
 * @param {string} [params.endDate] - End date (ISO format)
 * @returns {Promise<Object>} Device breakdown statistics
 */
export const getDeviceBreakdown = async (params = {}) => {
  const queryParams = new URLSearchParams();
  if (params.startDate) queryParams.append('start_date', params.startDate);
  if (params.endDate) queryParams.append('end_date', params.endDate);
  
  const queryString = queryParams.toString();
  const url = `/analytics/devices/${queryString ? `?${queryString}` : ''}`;
  
  const response = await apiClient.get(url);
  return response.data;
};

/**
 * Get visits time series data for graphing
 * @param {Object} params - Query parameters
 * @param {string} params.startDate - Start date (ISO format)
 * @param {string} params.endDate - End date (ISO format)
 * @param {string} [params.granularity='day'] - 'hour', 'day', 'week', 'month'
 * @returns {Promise<Array>} Time series data points
 */
export const getVisitsTimeSeries = async (params = {}) => {
  const queryParams = new URLSearchParams();
  if (params.startDate) queryParams.append('start_date', params.startDate);
  if (params.endDate) queryParams.append('end_date', params.endDate);
  if (params.granularity) queryParams.append('granularity', params.granularity);
  
  const queryString = queryParams.toString();
  const url = `/analytics/time-series/${queryString ? `?${queryString}` : ''}`;
  
  const response = await apiClient.get(url);
  return response.data;
};

/**
 * Get hourly traffic pattern
 * @param {Object} params - Query parameters
 * @param {string} [params.startDate] - Start date (ISO format)
 * @param {string} [params.endDate] - End date (ISO format)
 * @returns {Promise<Object>} Hourly traffic pattern (hour -> count)
 */
export const getHourlyPattern = async (params = {}) => {
  const queryParams = new URLSearchParams();
  if (params.startDate) queryParams.append('start_date', params.startDate);
  if (params.endDate) queryParams.append('end_date', params.endDate);
  
  const queryString = queryParams.toString();
  const url = `/analytics/hourly/${queryString ? `?${queryString}` : ''}`;
  
  const response = await apiClient.get(url);
  return response.data;
};

/**
 * Get top referrers
 * @param {Object} params - Query parameters
 * @param {string} [params.startDate] - Start date (ISO format)
 * @param {string} [params.endDate] - End date (ISO format)
 * @param {number} [params.limit=10] - Maximum referrers to return
 * @returns {Promise<Array>} Referrer statistics
 */
export const getReferrerStats = async (params = {}) => {
  const queryParams = new URLSearchParams();
  if (params.startDate) queryParams.append('start_date', params.startDate);
  if (params.endDate) queryParams.append('end_date', params.endDate);
  if (params.limit) queryParams.append('limit', params.limit.toString());
  
  const queryString = queryParams.toString();
  const url = `/analytics/referrers/${queryString ? `?${queryString}` : ''}`;
  
  const response = await apiClient.get(url);
  return response.data;
};

/**
 * Get recent visits for live monitoring
 * @param {Object} params - Query parameters
 * @param {number} [params.limit=50] - Maximum visits to return
 * @param {string} [params.path] - Optional path filter
 * @returns {Promise<Array>} Recent visit records
 */
export const getRecentVisits = async (params = {}) => {
  const queryParams = new URLSearchParams();
  if (params.limit) queryParams.append('limit', params.limit.toString());
  if (params.path) queryParams.append('path', params.path);
  
  const queryString = queryParams.toString();
  const url = `/analytics/recent/${queryString ? `?${queryString}` : ''}`;
  
  const response = await apiClient.get(url);
  return response.data;
};

/**
 * Get comprehensive analytics summary for dashboard
 * @param {Object} params - Query parameters
 * @param {string} [params.period='week'] - 'today', 'week', 'month', 'year'
 * @returns {Promise<Object>} Analytics summary with visits, devices, top pages
 */
export const getAnalyticsSummary = async (params = {}) => {
  const queryParams = new URLSearchParams();
  if (params.period) queryParams.append('period', params.period);
  
  const queryString = queryParams.toString();
  const url = `/analytics/summary/${queryString ? `?${queryString}` : ''}`;
  
  const response = await apiClient.get(url);
  return response.data;
};

/**
 * Export website analytics from currently loaded data.
 * @param {Object} params
 * @param {Object} params.analytics - Loaded analytics payload
 * @param {string} [params.period='week'] - Current selected period
 * @param {string} [params.format='csv'] - csv|excel
 * @param {string} [params.generatedBy='admin'] - User identifier for metadata
 * @returns {{blob: Blob, filename: string}}
 */
export const exportWebsiteAnalytics = ({
  analytics,
  period = 'week',
  format = 'csv',
  generatedBy = 'admin',
} = {}) => {
  const csvContent = buildWebsiteAnalyticsCsv(analytics || {}, {
    period,
    generatedBy,
  });

  const blobType = format === 'excel' ? 'application/vnd.ms-excel' : 'text/csv';
  const extension = format === 'excel' ? 'xls' : 'csv';
  const dateStamp = new Date().toISOString().slice(0, 10).replace(/-/g, '');
  return {
    blob: new Blob([csvContent], { type: blobType }),
    filename: `website_analytics_${period}_${dateStamp}.${extension}`,
  };
};

// Export all functions as default object as well
export default {
  getVisitStatistics,
  getPageAnalytics,
  getDeviceBreakdown,
  getVisitsTimeSeries,
  getHourlyPattern,
  getReferrerStats,
  getRecentVisits,
  getAnalyticsSummary,
  exportWebsiteAnalytics,
};
